

CREATE TABLE IF NOT EXISTS salones (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       TEXT        NOT NULL,
  capacidad    INT         NOT NULL,
  multimedia   TEXT        NOT NULL DEFAULT '',
  novedades    TEXT        NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS eventos (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_salon      INT         NOT NULL REFERENCES salones(id) ON DELETE CASCADE,
  titulo        TEXT        NOT NULL,
  encargado     TEXT        NOT NULL,
  fecha_inicio  TIMESTAMPTZ NOT NULL,
  fecha_fin     TIMESTAMPTZ NOT NULL,
  repeticion    TEXT        NOT NULL DEFAULT 'no',
  cupo          INT         NOT NULL,
  color         TEXT        NOT NULL DEFAULT '#3b82f6',
  CONSTRAINT chk_fechas_evento CHECK (fecha_fin > fecha_inicio)
);

CREATE INDEX IF NOT EXISTS idx_eventos_salon_fecha
  ON eventos (id_salon, fecha_inicio, fecha_fin);

CREATE TABLE IF NOT EXISTS usuarios (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre     TEXT    NOT NULL,
  -- Si activaste CITEXT arriba, cambia TEXT -> CITEXT
  correo     TEXT    NOT NULL UNIQUE,
  contrasena TEXT    NOT NULL,    -- (renombrada) guarda hash, no texto plano
  rol        TEXT    NOT NULL CHECK (rol IN ('admin','invitado'))
);
